spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/parkingdb}
    username: ${PGUSER:parking}
    password: ${PGPASSWORD:parking}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0
