spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:parkingdb}
    username: ${PGUSER:parking}
    password: ${PGPASSWORD:parking}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0
